### ISSUE TITLE
[UR/FR] 一种不干扰原有官方docker-compose.yml的服务器加载方式

### ISSUE THREAD

**Issue by GoFightNow** [Izumiko/jellyfin-danmaku#66]
我在看了README的几种加载方式后，总感觉对官方的entrypoint修改不太好，毕竟哪天改了就。。。
我想能不能在官方容器启动并健康后创建一个小容器运行一条命令之后就退出掉，想来想去就琢磨出下面这个docker-compose.yml。
缺点就是，你更新了jellyfin的镜像之后不能只docker compose up -d，因为这样jellyfin-danmaku不会随着重启。只能docker down后重新docker up -d。
我是想把镜像换成Alpine来着，但是发现就算把docker映射进去也没办法执行，可能是支持库的问题，我对这方面属实不太了解，所以最终用了debian的小镜像，但仍旧高达75MB。（这点希望有能力的大佬看到能再优化一下）

PS：感觉有点像[4. 修改服务端](https://github.com/Izumiko/jellyfin-danmaku?tab=readme-ov-file#4-%E4%BF%AE%E6%94%B9%E6%9C%8D%E5%8A%A1%E7%AB%AF)的脱裤子放屁版
```yaml
services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"
    group_add:
      - "103"
      - "44"
    ports:
      - 8096:8096
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./jellyfin_config:/config
      - ./jellyfin_cache:/cache
      - ./jellyfin_media:/media
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - TZ=Asia/Shanghai
      - http_proxy=http://科学
      - https_proxy=http://科学
      - no_proxy=localhost,127.0.0.1
    devices:
      - /dev/dri:/dev/dri
    restart: 'unless-stopped'

  jellyfin-danmaku:
    image: debian:bookworm-slim
    container_name: add_danmaku_js
    privileged: true
    user: root
    restart: no
    depends_on:
      jellyfin:
        condition: service_healthy
    volumes:
      - /usr/bin/docker:/usr/bin/docker:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command: 'docker exec -uroot jellyfin bash -c ''sed -i "s#</div></body>#</div><script src="https://jellyfin-danmaku.pages.dev/ede.user.js" defer></script></body>#" $$JELLYFIN_WEB_DIR/index.html'''
```
